[package]
name = "zkevm_test_harness"
version = "0.1.0"
edition = "2021"

resolver = "2"

[dependencies]
# zk_evm = {path = "../zk_evm"}
# sync_vm = {path = "../sync_vm", features = ["external_testing"]}
# zkevm-assembly = {path = "../zkEVM-assembly"}
# circuit_testing = {path = "../circuit_testing"}

zkevm-assembly = {git = "https://github.com/matter-labs/zkEVM-assembly.git", branch = "v1.1.1"}
zk_evm = {git = "https://github.com/matter-labs/zk_evm.git", branch = "v1.1.1"}
sync_vm = {git = "https://github.com/matter-labs/sync_vm.git", branch = "v1.1.1", features = ["external_testing"]}
circuit_testing = {git = "https://github.com/matter-labs/circuit_testing.git", branch = "main"}

num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
rayon = "*"
derivative = "*"
hex = "*"
blake2 = "0.10"
sha3 = "0.10"
sha2 = "0.10"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
crossbeam = "0.8"
bincode = "*"
