[package]
name = "circuit_definitions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zk_evm = {path = "../../zk_evm"}
boojum = {path = "../../boojum"}
zkevm_circuits = {path = "../../zkevm_circuits"}

# zkevm_circuits = {git = "https://github.com/matter-labs/zkevm_circuits.git", branch = "main"}
# zk_evm = {git = "https://github.com/matter-labs/zk_evm.git", branch = "v1.4.0"}
# boojum = {git = "https://github.com/matter-labs/boojum.git", branch = "main"}

derivative = "*"
serde = {version = "1", features = ["derive"]}
crossbeam = "0.8"
