on:
  push:
    branches: ["v1.3.0"]
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Target branch to generate geometry config against"
        type: string
        required: true
        default: "v1.3"
      circuit_type:
        description: "Numeric value of circuit type for which estimation is done"
        type: string
        required: true
        default: "3"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  estimate-circuit-limit:
    runs-on: [self-hosted, ci-runner]
    strategy:
      matrix:
        key: [${{ github.circuit_type }}]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
        with:
          ref: ${{ github.event.inputs.target_branch }}
          submodules: "recursive"
          token: ${{ secrets.ZKSYNC_ADMIN_BOT_ORG_REPO_WRITE }}
      - name: Setup Rust
        run: |
          curl https://sh.rustup.rs -sSf | bash -s -- -y
          source "$HOME/.cargo/env"
          sudo apt update && sudo apt install clang openssl libssl-dev gcc g++ pkg-config build-essential libclang-dev -y
      - name: Estimate circuit limit
        run: |
          git config --global --add url."https://${{ secrets.ZKSYNC_ADMIN_BOT_ORG_REPO_WRITE }}:x-oauth-basic@github.com/".insteadOf ssh://git@github.com/
          git config --global --add url."https://${{ secrets.ZKSYNC_ADMIN_BOT_ORG_REPO_WRITE }}:x-oauth-basic@github.com/".insteadOf https://github.com/
          source "$HOME/.cargo/env"
          cargo run --release --bin circuit_limit_estimator -- --numeric-circuit ${{ matrix.key }}
      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3
        with:
          path: ./circuit_limit_${{ matrix.key }}.txt
